📦 react-ebi-species 💬 Import package (#1)
* first commit

* Fix links in readme

* Move the dist directory inside html to host on github pages

* Use https in css to avoid mixed content errors

* Drosophila is not an animal, do not duplicate it

* Zea mays has its own icon. Danio rerio shows in blue. Change names for a group of species because they're not actual biological kingdoms. Prefix css so it doesn't collide with other styles.

* Bump package version 0.0.2

* Add species from www.ebi.ac.uk/gxa/baseline/experiments to this mapping as well. Extend readme.

* Bump package version 0.03

* Change CSS class name to something unique so that it doesn't clash with ebi-visual style it's taken from

* Bump package version 0.0.4

* Add one more species that we missed

* Bundles

* 0.0.5

* Add yeast icon

* 0.0.6

* Two more generic plant icons

* 0.0.7

* Use babel through presets

* 0.1.0

* Extra config for brewing yeast

* Update demo script

* Bundles

* 0.1.1

* Merge pull request #2 from alfonsomunozpomer/master

Remove unnecessary CSS attributes

* Merge pull request #1 from khawkins98/patch-1

Reference versioned font files

* 0.1.2

* Allow new versions of react

* Bundles

* 0.2.0

* Generic .gitignore file for NPM packages

* Add mappings, and fix some others, for font version 1.2 http://www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.2/

* Rename and convert to a stateless functional component, use prop-types package

* Lookup functions are part of the mapping file, add a few tests

* Update font to v1.2

* Export the React component as default and the render helper function

* Update dependencies, scripts and Webpack config file

* Move test to __test__ dir so that lib doesn’t become polluted

* A better demo that uses both the component and the rendering helper method

* A better demo that uses both the component and the rendering helper method

* Scripts and Webpack configuration to include bundles as part of the build process

* Polish documentation, update links, etc.

* Add bundles and Babelized files

* Script now superseded by npm run

* 1.0.0

* Use Babel --copy-files for CSS files

* 1.1.0

* Switch build tool to yarn

* v1.2.3

* Fix import

* NPM ignore lib

* Get jest to run, and add to prepublish - I am deeply troubled that including array-includes was required Tweak build tasks

* Merge pull request #3 from gxa/master

* 1.2.2

* Mocks after Jest docs

* Ignore build files

* Upgrade dependencies

* v1.2.4

* No need for array-includes plugin

* v1.2.5

* Update README.md

* A new major version of React EBI Species (#4)

* Replace prepublishOnly for prepack to ease testing as local package

* Streamline package publishing

* Update repository URL

* Move away from Yarn
To be consistent with the rest of our codebase

* Update to the very latest dependencies (Bael 7 included)

* Use new Babel 7 preset syntax/repository layout

* Switch roles in version 2
We can spare Wojtech from answering any pleas for support :)

* Some useful scripts to type less

* Use styled-components instead of CSS

* Update Jest toolchain to use Babel 7

* Use red icons to indicate warm-blooded animals
This gave rise to heated controversy within the Gene Expression group in
the EBI but we can now have a red chicken ;)

* Replace Webpack config with Webpack 4/WDS 3 compatible settings

* Update snapshots

* Update documentation

* Use official resources from EBI’s CDN

* Added a few more mappings to match the official EBI Icon Font docs

* Finches are warm-blooded too

* Sort species alphabetically by “official” name

* Add a second component that injects all styles without the need of an external CSS in the environment

* Make the default component assume the EBI VF CSS are loaded and use classes

* Add a demo page for the “bare” component

* Make two demo pages for each flavour of the component; show off all the capabilities of the component

* Remove CSS loaders

* Minor edits for consistency

* Remove SVG section from copy-pasted Webpack config

* Use global styles as intended; render a nice question mark if a species can’t be mapped to an icon

* Do not wrap a <span> within a <span> (yo Dawg)

* Don’t use createGlobalStyle, as it’s rendered multiple times
We can keep the number of classes to the minimum (4) removing props from
the styled component

* Fix undefined reference to earlier component

* Show unknown species symbol without conditional rendering

* Simplify creation of all species array and export it without a wrapper function

* Simplify demo generator

* Wrap all tests in a describe block and use allSpecies array

* Don’t export lookUpIcon as a default mapping.js is a bit of mixed bag of stuff, it doesn’t follow naturally that lookUpIcon should be the default

* Add test for the bare component

* Add a test to check that each component uses or doesn’t use EBI VF class names

* Update snapshots

* Update badges to use the GE team URL

* Produce two bundles, one for each flavour of the component

* Bigger, better, more accurate documentation

* Minor rewording

* 2.0.0-beta

* Delete broken badge Markdown

* Fix coverage badge URL

* Fix README after PR review #4

* 2.0.0

* V2.1.0 (#5)

* Update dependencies and remove boilerplate code in tests

* Add new mappings for mosquito and plasmodium species

* Tidy up npm scripts

* 2.1.0

* Full compliance with EBI Icon Fonts 1.3.0 (#6)

* Update mappings and demo pages to EBI Icon fonts v1.3

* Update dependencies

* 2.2.0

* Update to latest dependencies

* 2.2.1

* Add org scope to package

* Update dependencies

* 2.3.0

* Update snapshots

* Update documentation

* 2.3.1