A new major version of React EBI Species (#4)
* Replace prepublishOnly for prepack to ease testing as local package

* Streamline package publishing

* Update repository URL

* Move away from Yarn
To be consistent with the rest of our codebase

* Update to the very latest dependencies (Bael 7 included)

* Use new Babel 7 preset syntax/repository layout

* Switch roles in version 2
We can spare Wojtech from answering any pleas for support :)

* Some useful scripts to type less

* Use styled-components instead of CSS

* Update Jest toolchain to use Babel 7

* Use red icons to indicate warm-blooded animals
This gave rise to heated controversy within the Gene Expression group in
the EBI but we can now have a red chicken ;)

* Replace Webpack config with Webpack 4/WDS 3 compatible settings

* Update snapshots

* Update documentation

* Use official resources from EBI’s CDN

* Added a few more mappings to match the official EBI Icon Font docs

* Finches are warm-blooded too

* Sort species alphabetically by “official” name

* Add a second component that injects all styles without the need of an external CSS in the environment

* Make the default component assume the EBI VF CSS are loaded and use classes

* Add a demo page for the “bare” component

* Make two demo pages for each flavour of the component; show off all the capabilities of the component

* Remove CSS loaders

* Minor edits for consistency

* Remove SVG section from copy-pasted Webpack config

* Use global styles as intended; render a nice question mark if a species can’t be mapped to an icon

* Do not wrap a <span> within a <span> (yo Dawg)

* Don’t use createGlobalStyle, as it’s rendered multiple times
We can keep the number of classes to the minimum (4) removing props from
the styled component

* Fix undefined reference to earlier component

* Show unknown species symbol without conditional rendering

* Simplify creation of all species array and export it without a wrapper function

* Simplify demo generator

* Wrap all tests in a describe block and use allSpecies array

* Don’t export lookUpIcon as a default mapping.js is a bit of mixed bag of stuff, it doesn’t follow naturally that lookUpIcon should be the default

* Add test for the bare component

* Add a test to check that each component uses or doesn’t use EBI VF class names

* Update snapshots

* Update badges to use the GE team URL

* Produce two bundles, one for each flavour of the component

* Bigger, better, more accurate documentation

* Minor rewording

* 2.0.0-beta

* Delete broken badge Markdown

* Fix coverage badge URL

* Fix README after PR review #4